# ===== Database cho ControlManagementDB =====
[databaseControlManagementDB]
host = 127.0.0.1
user = root
password = 
database = ControlManagementDB
port = 3306

# ===== Database cho Performance_Staging =====
[databasePerformance_Staging]
host = 127.0.0.1
user = root
password = 
database = Performance_Staging
port = 3306


# ===== Database cho DataWarehouse =====
[databaseDataWarehouseDB]
host = 127.0.0.1
user = root
password = 
database = DataWarehouseDB
port = 3306


# ===== Database cho Player_Performance_Mart =====
[databasePlayer_Performance_Mart]
host = 127.0.0.1
user = root
password = 
database = Player_Performance_Mart
port = 3306



[scheduler]
enabled = true
interval_hours = 24

[email]
smtp_server = smtp.gmail.com
smtp_port = 587
sender = tuansdev@gmail.com
password = uzfp jegb wese bgif
receiver = 22130313@st.hcmuaf.edu.vn
